apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data-pvc
  labels:
    app: opencloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
