{{- if false }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice-tlsroute
  namespace: {{ include "opencloud.namespace" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: onlyoffice-tls
  hostnames:
    - {{ .Values.global.domain.onlyoffice | quote }}
  rules:
    - backendRefs:
        - name: {{ include "opencloud.fullname" . }}-onlyoffice
          port: 443
{{- end }}
