{{- if false }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice-httproute-echo
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: onlyoffice-https
  hostnames:
    - {{ .Values.global.domain.onlyoffice | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: echo-1
          port: 8080
{{- end }}
