{{- if .Values.onlyoffice.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice-config
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
data:
  entrypoint-override.sh: {{ .Files.Get "files/onlyoffice/entrypoint-override.sh" | quote }}
  local.json: {{ tpl (.Files.Get "files/onlyoffice/local.json.gotmpl") . | quote }}
{{- end }}
