{{- if and .Values.onlyoffice.enabled (or (and .Values.ingress.enabled (eq .Values.ingress.annotationsPreset "traefik")) (and .Values.httpRoute.enabled (eq .Values.httpRoute.gateway.className "traefik"))) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-x-forwarded-proto-https
  namespace: {{ include "opencloud.namespace" . }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end}}
