{{- if .Values.opencloud.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-config
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
data:
  # App registry configuration
  app-registry.yaml: {{ .Files.Get "files/opencloud/app-registry.yaml" | quote }}

  # CSP configuration
  csp.yaml: {{ tpl (.Files.Get "files/opencloud/csp.yaml.gotmpl") . | quote }}

  # Banned password list
  banned-password-list.txt: {{ tpl (.Files.Get "files/opencloud/banned-password-list.txt.gotmpl") . | quote }}

  # Search configuration
  search.yaml: {{ .Files.Get "files/opencloud/search.yaml" | quote }}
{{- end }}
